AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: production-v200-2
Resources:
  RainforestProcessIncoming:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: rainforest.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: production-v200-2
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::547053441796:role/Rainforest-Gateway-Role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /api/meters/rainforest
            Method: ANY
